elastic-erga:
  build: .
  ports:
   - "10080:80"
  links:
   - mysql
  environment:
   - APP_ENV=local
   - APP_DEBUG=true

mysql:
  image: mysql
  ports:
   - "13306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=unsafe-local-dev-only
    - MYSQL_USER=elastic_erga
    - MYSQL_PASSWORD=elastic_erga
    - MYSQL_DATABASE=elastic_erga

elasticsearch:
  image: elasticsearch
  ports:
    - "19200:9200"
